/*******************************************
 * data: 2016-12-20
 * auth: Rhaegar
 * desc: System enum item
 *******************************************/
 
IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME = 'CBMGR_TB_SysEnumItem')
DROP TABLE CBMGR_TB_SysEnumItem
GO

CREATE TABLE CBMGR_TB_SysEnumItem
(
	[ITME_ID] INT IDENTITY PRIMARY KEY NOT NULL
	,[TYPE_ID] INT NOT NULL 
	,[ITEM_NAME] NVARCHAR(20) NOT NULL
	,[CREATE_DATE] DATETIME NOT NULL
	,[COMMENT] NVARCHAR(200) NULL
	,[ENABLED] BIT NOT NULL DEFAULT 1
)

INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'所有人',GETDATE(),N'球会所有人',1)
INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'管理员',GETDATE(),N'球会管理员',1)
INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'会员',GETDATE(),N'球会会员',1)
INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'散客',GETDATE(),N'散客',1)
INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'自定义1',GETDATE(),N'自定义级别1',0)
INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'自定义2',GETDATE(),N'自定义级别2',0)
INSERT INTO CBMGR_TB_SysEnumItem([TYPE_ID],ITEM_NAME,CREATE_DATE,COMMENT,[ENABLED])VALUES(1,N'自定义3',GETDATE(),N'自定义级别3',0)