/*******************************************
 * data: 2016-12-21
 * auth: Rhaegar
 * desc: Create a new club
 *******************************************/
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='CBMG_SP_CreateNewClub')
 DROP PROCEDURE CBMG_SP_CreateNewClub
 GO
 
 CREATE PROCEDURE CBMG_SP_CreateNewClub
 @CREATEOT_ID VARCHAR(50)
 ,@CLUB_NAME NVARCHAR(16)
 ,@COMMENT NVARCHAR(200)
 AS
 BEGIN
 	DECLARE @CID VARCHAR(50) SET @CID = NEWID()
 	DECLARE @GID VARCHAR(50) SET @GID = NEWID()
 	BEGIN TRY
 		BEGIN TRANSACTION
 		--Club info
 		INSERT INTO CBMGR_TB_ClubInfo
 		(CLUB_ID, CLUB_NAME, CREATOR_ID, CREATOR_DATE, OWNER_ID, PIC_SRC, COMMENT)
 		VALUES
 		(@CID, @CLUB_NAME, @CREATEOT_ID, GETDATE(), @CREATEOT_ID, '', @COMMENT)
 		--Default ground info
 		INSERT INTO CBMGR_TB_GroundInfo
 		( GROUND_ID, CLUB_ID, GROUND_NAME, CREATE_DATE, ENALBED )
 		VALUES
 		( @GID, @CID, '³¡µØ1', GETDATE(), 0 )
 		--Defalut level info
 		INSERT INTO CBMGR_TB_UserLevelToGround
 		( ID, GROUND_ID, LEVEL_ID, CREATE_DATE, MODIFY_DATE )
 		VALUES
 		( NEWID(), @GID, 1, GETDATE(), GETDATE() )
 		INSERT INTO CBMGR_TB_UserLevelToGround
 		( ID, GROUND_ID, LEVEL_ID, CREATE_DATE, MODIFY_DATE )
 		VALUES
 		( NEWID(), @GID, 2, GETDATE(), GETDATE() )
 		INSERT INTO CBMGR_TB_UserLevelToGround
 		( ID, GROUND_ID, LEVEL_ID, CREATE_DATE, MODIFY_DATE )
 		VALUES
 		( NEWID(), @GID, 3, GETDATE(), GETDATE() )
 		INSERT INTO CBMGR_TB_UserLevelToGround
 		( ID, GROUND_ID, LEVEL_ID, CREATE_DATE, MODIFY_DATE )
 		VALUES
 		( NEWID(), @GID, 4, GETDATE(), GETDATE() )
 		COMMIT
 	END TRY
 	BEGIN CATCH
 		ROLLBACK
 		SELECT 0 AS RESULT, ERROR_MESSAGE() AS MSG, NULL AS CLUBID
 	END CATCH
 END