/*******************************************
 * data: 2018-04-17
 * auth: Rhaegar
 * desc: Create a app key
 *******************************************/
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='CM_SP_CreateAppKey')
 DROP PROCEDURE CM_SP_CreateAppKey
 GO
 
 CREATE PROCEDURE CM_SP_CreateAppKey
 @EMAIL VARCHAR(100),
 @KEY_VALUE VARCHAR(200)
 AS
 BEGIN
	BEGIN TRY
		DECLARE @NOW DATETIME SET @NOW = GETDATE()
		INSERT INTO CM_Sys_AppKey
		([KEY_VALUE], [EMAIL], [CREATE_DATE], [LAST_REQUIRED], [ENABLED], [COMMENT])
		VALUES
		(@KEY_VALUE, @EMAIL, @NOW, @NOW, 1, '')
		SELECT 1 AS RESULT, NULL AS MSG
	END TRY
 	BEGIN CATCH
 		SELECT 0 AS RESULT, ERROR_MESSAGE() AS MSG
 	END CATCH
 END