/*******************************************
 * data: 2016-12-22
 * auth: Rhaegar
 * desc: Create a game
 *******************************************/
 IF EXISTS(SELECT NAME FROM SYSOBJECTS WHERE NAME='CM_SP_CreateGame')
 DROP PROCEDURE CM_SP_CreateGame
 GO
 
 CREATE PROCEDURE CM_SP_CreateGame
 @CREATEOT_ID VARCHAR(50)
 ,@CLUB_ID VARCHAR(50)
 ,@GROUND_ID VARCHAR(50)
 ,@GAME_TITLE NVARCHAR(20) = ''
 ,@BEGIN_DATE DATETIME
 ,@END_DATE DATETIME
 ,@LOCK_DATE DATETIME = NULL
 ,@MAX_NUM INT = -1
 ,@G_COUNT INT
 ,@P_COUNT INT = 6
 ,@BALL_INFO NVARCHAR(50) = NULL
 ,@COMMENT NVARCHAR(200) = NULL
 AS
 BEGIN
 	BEGIN TRY
 		--Get default game title
 		IF @GAME_TITLE IS NULL
 		BEGIN
 			SELECT @GAME_TITLE = CLUB_NAME FROM CM_ClubInfo WHERE CLUB_ID = @CLUB_ID
 			SET @GAME_TITLE = @GAME_TITLE + N'日常活动'
 		END
 		--Get default lock date
 		IF @LOCK_DATE IS NULL
 		BEGIN
 			SET @LOCK_DATE = @BEGIN_DATE
 		END
 		--Create game info
 		INSERT INTO CM_GameInfo
 		( GAME_ID, CLUB_ID, GROUND_ID, GAME_TITLE, CREATOR_ID, BEGIN_DATE, END_DATE, LOCK_DATE, MAX_ATTACH_NUMBER, GROUND_COUNT, PERSON_PER_GROUND, BALL_INFO, GAME_STATE, COMMENT )
 		VALUES
 		( NEWID(), @CLUB_ID, @GAME_TITLE, @GROUND_ID, @CREATEOT_ID, @BEGIN_DATE, @END_DATE, @LOCK_DATE, @MAX_NUM, @G_COUNT, @P_COUNT, @BALL_INFO, 1, @COMMENT )
 		--Operation result
 		SELECT 1 AS RESUTL, @@IDENTITY AS GAME_ID, '' AS MSG
 	END TRY
 	BEGIN CATCH
  		SELECT 0 AS RESUTL, NULL AS GAME_ID, ERROR_MESSAGE() AS MSG
 	END CATCH
 END